# sim.toml is an override: all data from config.toml is loaded first,
# then data from sim.toml overwrites data from config.toml
# this also means if you have something like
# [myData]
# value = 1
# [myData/something]
# someDat = 2
#
#and you overwrite [myData]/value here, you'll delete [myData/something] because it is overwritten
[swerve]
ks = 3