# startup stuff
[leftFlywheelGen]
[rightFlywheelGen]

# Disabler
[disabler]
vision_disabled = true
drive_disabled = false
flywheel_disabled = false
odometry_disabled = false
climber_disabled = true
groundIntake_disabled = false
nms_disabled = false
pivot_disabled = true

# Commands
[commands]
ramFire_speed = 60
groupDeadline_seconds = 4
groundIntake_nominalVoltage = 9
noteManagement_nominalVoltage = 2
skip_intermediates = false

# Ground Intake
[ground_intake.top]
id = 15
rotationToMeterCoef = 1
encoderToMechanismCoef = 1
rotationalInertia = 1
inverted = true
currentLimit = 40

[ground_intake.bottom]
id = 21
rotationToMeterCoef = 1
encoderToMechanismCoef = 1
rotationalInertia = 1
inverted = true
currentLimit = 40

[ground_intake.ff_top]
startDelay_ms = 1000
endVoltage = 12
rampRate_vPerMs = 0.0008

[ground_intake]
ff_ks = 0
ff_kv = 0
pid = {p = 0, i = 0, d = 0,  tolerance = 0}

# flywheel
[flywheel]
velocity_pid = {p = 0.06, i = 0, d = 0.75, tolerance = 0}

[flywheel.left]
id = 4
encoderToMechanismCoef = 1
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
inverted = true
ff = { ks = 0.5477470887299486, kv = 0.12995659292230272 }
encoder = { dio_channelA = 7, dio_channelB = 8, encoderToMechanismCoef = 1, inverted = false }


[flywheel.right]
id = 7
encoderToMechanismCoef = 1
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
inverted = false
ff = { ks = 0.6505197479235123, kv = 0.12757668962958083 }
encoder = { dio_channelA = 0, dio_channelB = 1, encoderToMechanismCoef = 1, inverted = true }



[flywheel.calculator]
mass = 0.25 #kg
area_cross_section = 0.4 #m;
note_radius = 17.78 #cm
air_density = 1.225 #kg/m^3
drag_coefficient = 1.3 #guess
magnus_coefficient = 0.2 #guess
Vx = 10 #m/s
Vy = 5 #m/s


# Pivot Stuff
[pivot]
encoder = { dio_channelA = 2, dio_channelB = 3, encoderToMechanismCoef = 1, inverted = true }
pid = {i = 0, p = 1, d = 0,  tolerance = 0}

[pivot.left]
encoderToMechanismCoef = 1666.666666666666666666666666666666666666666666 # 100:1 * 15:18 * 20:1
id = 5 #right = 8
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
currentLimit = 20
inverted = true
breakModeEnabled = true

[pivot.right]
encoderToMechanismCoef = 1666.666666666666666666666666666666666666666666 # 100:1 * 15:18 * 20:1
id = 8
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
currentLimit = 20
inverted = false
breakModeEnabled = true


# DRIVE STUFF GOES HERE
[swerve]
steer_pid_common = {p = 4, i = 0, d = 0.3,  tolerance = 0.00555556} # pi / 90 -> rots
x_holonomic_pid = {p = 2.55, i = 0, d = 0.05,  tolerance = 0}
y_holonomic_pid = {p = 2.55, i = 0, d = 0.05,  tolerance = 0}
t_holonomic_pid = {p = 2.45, i = 0, d = 0.05,  tolerance = 0} #need to be redone (current mcr values)
drive_pid_common = {p = 0.006, i = 0, d = 0.0,  tolerance = 0}
ff_fl = {ks = 0.045, kv = 2.505}
ff_fr = {ks = 0.056, kv = 2.532}
ff_br = {ks = 0.044, kv = 2.496}
ff_bl = {ks = 0.044, kv = 2.516}
use_velocity_pid_teleop = false
use_offset_finding_mode = false
p_heading = 0.04

[operatorToSpeeds]
field_oriented = true
turbo_speed_multiplier = 5
normal_speed_multiplier = 4.5
slow_speed_multiplier = 3

[odometry]
pigeon_can_id = 5
centroid_height = 0 #TODO
camera_centroid_offset = {x = 0, y = 0, z = 0} #TODO
fl_pos_offset = {x = 0.2286, y = 0.3429}
fr_pos_offset = {x = 0.2286, y = -0.3429}
bl_pos_offset = {x = -0.3556, y = 0.3429}
br_pos_offset = {x = -0.3556, y = -0.3429}

# SWERVE STEERING
[swerve.steer_common]
encoderToMechanismCoef = 0.078125 # (14.0 / 50.0) * (10.0 / 60.0) mk4i reduction
rotationalInertia = 0.002
inverted = false
breakModeEnabled = true
currentLimit = 30

[swerve.steer_fr]
id = 9
[swerve.steer_fl]
id = 20
[swerve.steer_br]
id = 14
[swerve.steer_bl]
id = 16

[swerve.drive_fr]
id = 2
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70
openRampRate = 0.5

[swerve.drive_fl]
id = 1
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70
openRampRate = 0.5

[swerve.drive_br]
id = 3
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70
openRampRate = 0.5


[swerve.drive_bl]
id = 6
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70
openRampRate = 0.5


# hypothesis: non offset zero is tangent to the absolute encoders?
# ALWAYS LOW BALL THESE OFFSETS (if its fluctuating between 0.8 and 0.9 go for 0.8
[swerve.abs_fr]
analog_channel = 3
offset = 0.371
encoderToMechanismCoef = 1

[swerve.abs_fl]
analog_channel = 0
offset = 0.341
encoderToMechanismCoef = 1

[swerve.abs_br]
analog_channel = 2
offset = 0.854
encoderToMechanismCoef = 1

[swerve.abs_bl]
analog_channel = 1
offset = 0.572
encoderToMechanismCoef = 1


# CLIMBER STUFF GOES HERE
[climber]
climber_pid = {p = 0, i = 0, d = 0,  tolerance = 0}
ff_kv = 0.0
ff_ks = 0.0

[climber.left]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

[climber.right]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

# NMS NOTE MANAGEMENT SUBSYSTEM
[nms]
channel = 5
deadband = 0 # FIX LATER

[nms.top]
id = 19
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0
breakModeEnabled = true
currentLimit = 30

[nms.bottom]
id = 17
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0
breakModeEnabled = true
currentLimit = 30


# CAMERA
[cameras]
camera1Name = "arducam1"
camera2Name = "arducam2"

