[absolute]
absolute_offset = 0.0
coefficient = 0.0
[swerve]
ks = 3
kv = 0.0
ka = 0.0

[swerve.steer_bl]
id = 0

[swerve.steer_fr]
id = 0

[swerve.steer_common]
sensor2mechanism_coef = 0.0
type = "BRUSHLESS"

[swerve.steer_br]
id = 0

[swerve.drive_bl]
id = 0

[swerve.drive_common]
sensor2mechanism_coef = 0.0
type = "BRUSHLESS"

[swerve.steer_fl]
id = 0

[swerve.drive_fl]
id = 0

[swerve.t_holonomic_pid]
p = 0
d = 0
i = 0

[swerve.drive_br]
id = 0

[swerve.y_holonomic_pid]
p = 0
d = 0
i = 0

[swerve.drive_fr]
id = 0

[swerve.steer_pid_common]
p = 0
d = 0
i = 0

[swerve.x_holonomic_pid]
p = 0
d = 0
i = 0
[shooter]
channel = 0

[shooter.wheel_1]
id = 0

[shooter.wheel_2]
id = 0

[shooter.common]
sensor2mechanism_coef = 0.0
id = 0
type = "BRUSHLESS"

[shooter.angle.pid]
p = 0
d = 0
i = 0

[climber]
dampner = 0.0
ka = 0.0
ks = 0.0
kv = 0.0

[climber.climber_pid]
p = 0
d = 0
i = 0

[climber.common]
sensor2mechanism_coef = 0.0
type = "BRUSHLESS"

[climber.left]
id = 0

[climber.right]
id = 0
