# Base Robot Stuff

[ground_intake.top]
id = 17
rotationToMeterCoef = 1
encoderToMechanismCoef = 1

[ground_intake.bottom]
id = 9
rotationToMeterCoef = 1
encoderToMechanismCoef = 1
inverted = true

[ground_intake.ff_top]
startDelay_ms = 1000
endVoltage = 12
rampRate_vPerMs = 0.0008

[ground_intake]
ff_ks = 0
ff_kv = 0
pid = {p = 0, i = 0, d = 0}

# SHOOTER

[shooter]
dio_channel = 0
deadband = 0.0
channel = 0

[shooter.wheel_1]
id = 0
encoderToMechanismCoef = 0.0

[shooter.wheel_2]
id = 0
encoderToMechanismCoef = 0.0

[shooter.absolute]
analogChannel = 0
encoderToMechanismCoef = 0.0
offset = 0.0

[shooter.angle.pid]
p = 0
d = 0
i = 0

[shooter.angle_motor]
encoderToMechanismCoef = 0.0
id = 0

# DRIVE STUFF GOES HERE

[swerve]
pigeonId = 5
ff_ks = 0.65292
ff_kv = 2.3053
ff_ka = 0.37626
magnitudeFWLim = 3.3
fl_offset = {x = 0.2286, y = 0.3429}
fr_offset = {x = 0.2286, y = -0.3429}
bl_offset = {x = -0.3556, y = 0.3429}
br_offset = {x = -0.3556, y = -0.3429}
x_holonomic_pid = {p = 1.2, i = 0, d = 0}
y_holonomic_pid = {p = 1.2, i = 0, d = 0}
t_holonomic_pid = {p = 1, i = 0, d = 0}

# Steer
[swerve.steer_common]
encoderToMechanismCoef = 0.078125 # (14.0 / 50.0) * (10.0 / 60.0) mk4i reduction
rotationalInertia = 0.002
inverted = false

[swerve.steer_fr]
id = 16
[swerve.steer_fl]
id = 17
[swerve.steer_br]
id = 21
[swerve.steer_bl]
id = 9

#Drive (mk4 l2 is same as mk4i)
[swerve.drive_fr]
id = 20
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = true

[swerve.drive_fl]
id = 15
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = true

[swerve.drive_br]
id = 19
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = true

[swerve.drive_bl]
id = 14
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false


[swerve.steer_pid_common]
p = 3
i = 0
d = 0.3

# hypothesis: non offset zero is tangent to the absolute encoders?

[swerve.abs_fr]
analogChannel = 0
offset = 0.379
encoderToMechanismCoef = 1

[swerve.abs_fl]
analogChannel = 3
offset = 0.3375
encoderToMechanismCoef = 1

[swerve.abs_br]
analogChannel = 1
offset = 0.845
encoderToMechanismCoef = 1

[swerve.abs_bl]
analogChannel = 2
offset = 0.0798
encoderToMechanismCoef = 1


# CLIMBER STUFF GOES HERE

[climber]
climber_pid = {p = 0, i = 0, d = 0}
ff_kv = 0.0
ff_ks = 0.0

[climber.left]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

[climber.right]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

# NMS NOTE MANAGEMENT SUBSYSTEM
[nms]
channel = 0
deadband = 0 # FIX LATER

[nms.top]
id = 0
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0

[nms.bottom]
id = 0
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0

# CAMERA

[cameras]
camera1Name = "arducam1"
camera2Name = "arducam2"

# Disabler

[disabler]
vision_disabled = true
drive_disabled = false
shooter_disabled = true
odometry_disabled = false
climber_disabled = true
groundIntake_disabled = true
nms_disabled = true

