# startup stuff
[shooter.wheel_1_ffgen]
[shooter.wheel_2_ffgen]

[swerve.ffgen_fr]
[swerve.ffgen_fl]
[swerve.ffgen_br]
[swerve.ffgen_bl]

# Base Robot Stuff

[ground_intake.top]
id = 17
rotationToMeterCoef = 1
encoderToMechanismCoef = 1
rotationalInertia = 1

[ground_intake.bottom]
id = 9
rotationToMeterCoef = 1
encoderToMechanismCoef = 1
rotationalInertia = 1
inverted = true

[ground_intake.ff_top]
startDelay_ms = 1000
endVoltage = 12
rampRate_vPerMs = 0.0008

[ground_intake]
ff_ks = 0
ff_kv = 0
pid = {p = 0, i = 0, d = 0}

# SHOOTER

[shooter]
dio_channel = 0
deadband = 0.0
channel = 0
pid = {p = 0, i = 0, d = 0}
ff_ks = 0.4895168812659137
ff_kv = 0.12869522412846462


[shooter.wheel_1]
id = 12
encoderToMechanismCoef = 1
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
pid = {p = 1, i = 0, d = 0}
inverted = true

[shooter.wheel_2]
id = 13
encoderToMechanismCoef = 1
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
pid = {p = 1, i = 0, d = 0}
inverted = false

[shooter.absolute]
analogChannel = 0
encoderToMechanismCoef = 1
offset = 0.0

[shooter.velocity]
analogChannel = 0
encoderToMechanismCoef = 1
offset = 0.0

[shooter.pivot]
encoderToMechanismCoef = 1
id = 11
rotationalInertia = 0.002
velocityStdv = 0.001
positionStdv = 0.001
pid = {p = 0, i = 0, d = 0}

[shooter.calculator]
mass = 0.25 #kg
area_cross_section = 0.4 #m;
note_radius = 17.78 #cm
air_density = 1.225 #kg/m^3
drag_coefficient = 1.3 #guess
magnus_coefficient = 0.2 #guess
Vx = 10 #m/s
Vy = 5 #m/s

# DRIVE STUFF GOES HERE

[swerve]
pigeonId = 5
magnitudeFWLim = 3.3
fieldOriented = true
x_holonomic_pid = {p = 1.2, i = 0, d = 0}
y_holonomic_pid = {p = 1.2, i = 0, d = 0}
t_holonomic_pid = {p = 4.4, i = 0, d = 0.4} #need to be redone (current mcr values)
steer_pid_common = {p = 3, i = 0, d = 0.3}
drive_pid_common = {p = 0.05, i = 0, d = 0.01}
ff_fl = {ks = 0.045, kv = 2.505}
ff_fr = {ks = 0.056, kv = 2.532}
ff_br = {ks = 0.044, kv = 2.496}
ff_bl = {ks = 0.044, kv = 2.516}

[odometry]
centroid_height = 0 #TODO
fl_pos_offset = {x = 0.2286, y = 0.3429}
fr_pos_offset = {x = 0.2286, y = -0.3429}
bl_pos_offset = {x = -0.3556, y = 0.3429}
br_pos_offset = {x = -0.3556, y = -0.3429}

# Steer
[swerve.steer_common]
encoderToMechanismCoef = 0.078125 # (14.0 / 50.0) * (10.0 / 60.0) mk4i reduction
rotationalInertia = 0.002
inverted = false
breakModeEnabled = false
currentLimit = 30


[swerve.steer_fr]
id = 16
[swerve.steer_fl]
id = 17
[swerve.steer_br]
id = 21
[swerve.steer_bl]
id = 9

#Drive (mk4 l2 is same as mk4i)
[swerve.drive_fr]
id = 2
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70

[swerve.drive_fl]
id = 1
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70



[swerve.drive_br]
id = 3
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70



[swerve.drive_bl]
id = 0
rotationToMeterCoef = 0.31519599093
encoderToMechanismCoef = 0.14823529411
rotationalInertia = 0.025
inverted = false
breakModeEnabled = true
currentLimit = 70



# hypothesis: non offset zero is tangent to the absolute encoders?
# ALWAYS LOW BALL THESE OFFSETS (if its fluctuating between 0.8 and 0.9 go for 0.8
[swerve.abs_fr]
analogChannel = 0
offset = 0.371
encoderToMechanismCoef = 1

[swerve.abs_fl]
analogChannel = 3
offset = 0.341
encoderToMechanismCoef = 1

[swerve.abs_br]
analogChannel = 1
offset = 0.854
encoderToMechanismCoef = 1

[swerve.abs_bl]
analogChannel = 2
offset = 0.572
encoderToMechanismCoef = 1


# CLIMBER STUFF GOES HERE

[climber]
climber_pid = {p = 0, i = 0, d = 0}
ff_kv = 0.0
ff_ks = 0.0

[climber.left]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

[climber.right]
id = 0
encoderToMechanismCoef = 0.0
rotationalInertia = 0.0

# NMS NOTE MANAGEMENT SUBSYSTEM
[nms]
channel = 2
deadband = 0 # FIX LATER

[nms.top]
id = 4
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0

[nms.bottom]
id = 7
rotationToMeterCoef = 1 #WRONG
encoderToMechanismCoef = 1 #WRONG
rotationalInertia = 1.0
inverted = true

# CAMERA

[cameras]
camera1Name = "arducam1"
camera2Name = "arducam2"

# actually get these values lmfao TODO
camera1TranslationOffset = {x = 0, y = 0, z = 1}
camera1RotationOffset = {x = 0, y = 0, z = 0, w = 0}

camera2TranslationOffset = {x = 0, y = 0, z = 1}
camera2RotationOffset = {x = 0, y = 0, z = 0, w = 0}

[NMS]
mechPerEncoderRotation = 0.0
metersPerRotation = 1
rotationalInertia = 0
id = 0
type = "BRUSHLESS"



# Disabler

[disabler]
vision_disabled = false
drive_disabled = false
shooter_disabled = true
odometry_disabled = true
climber_disabled = true
groundIntake_disabled = true
nms_disabled = true
