# Base Robot Stuff

[ground_intake.top]
id = 17
metersPerRotation = 1
mechPerEncoderRotation = 1
type = "BRUSHLESS"

[ground_intake.bottom]
id = 9
metersPerRotation = 1
mechPerEncoderRotation = 1
type = "BRUSHLESS"
inverted = true

[ground_intake.ff_top]
startDelay_ms = 0
endVoltage = 12
rampRate_vPerMs = 0.001

[ground_intake.ffgen_bottom]
startDelay_ms = 50
endVoltage = 0
rampRate_vPerMs = 0


[ground_intake]
ff_ks = 0
ff_kv = 0
pid = {p = 0, i = 0, d = 0}

[absolute]
analogChannel = 0
coefficient = 0.0
absoluteOffset = 0.0

[shooter]
dio_channel = 0
deadband = 0.0
channel = 0

[shooter.wheel_1]
id = 0

[shooter.wheel_2]
id = 0

[shooter.common]
mechPerEncoderRotation = 0.0
type = "BRUSHLESS"

[shooter.angle.pid]
p = 0
d = 0
i = 0

[shooter.angle_motor]
mechPerEncoderRotation = 0.0
id = 0
type = "BRUSHLESS"

# DRIVE STUFF GOES HERE

[swerve]
x_holonomic_pid = {p = 0, i = 0, d = 0}
y_holonomic_pid = {p = 0, i = 0, d = 0}
t_holonomic_pid = {p = 0, i = 0, d = 0}
pigeonId = 5
ks = 0.0
kv = 0.0
halfWidth = 0.0
halfBase = 0.0

[swerve.steer_fr]
id = 0
[swerve.steer_fl]
id = 0
[swerve.steer_br]
id = 0
[swerve.steer_bl]
id = 0
[swerve.drive_fr]
id = 0
[swerve.drive_fl]
id = 0
[swerve.drive_br]
id = 0
[swerve.drive_bl]
id = 0

[swerve.steer_common]
metersPerRotation = 0
mechPerEncoderRotation = 0
type = "BRUSHLESS"
positionStdv = 0.0
rotationalInertia = 0.0
velocityStdv = 0.0

[swerve.drive_common]
metersPerRotation = 0
mechPerEncoderRotation = 0.0
type = "BRUSHLESS"
positionStdv = 0.0
rotationalInertia = 0.0
velocityStdv = 0.0


[swerve.steer_pid_common]
p = 0
d = 0
i = 0

# CLIMBER STUFF GOES HERE

[climber]
climber_pid = {p = 0, i = 0, d = 0}
kv = 0.0
ks = 0.0

[climber.left]
id = 0
mechPerEncoderRotation = 0.0
type = "BRUSHLESS"
positionStdv = 0.0
rotationalInertia = 0.0
velocityStdv = 0.0

[climber.right]
id = 0
mechPerEncoderRotation = 0.0
type = "BRUSHLESS"
positionStdv = 0.0
rotationalInertia = 0.0
velocityStdv = 0.0

[cameras]
camera1Name = "arducam1"
camera2Name = "arducam2"

# Disabler

[disabler]
vision_disabled = true
drive_disabled = false
shooter_disabled = true
odometry_disabled = true
climber_disabled = true
groundIntake_disabled = true

