# mcr data goes here

[odometry]
#THIS IS WRONG
fl_pos_offset = {x = 0.2318, y = 0.26035}
fr_pos_offset = {x = 0.2318, y = -0.26035}
bl_pos_offset = {x = -0.2318, y = 0.26035}
br_pos_offset = {x = -0.2318, y = -0.26035}

[swerve]
ff_ks = 0.24576726513236846
ff_kv = 2.7734372496807604


[swerve.steer_common]
encoderToMechanismCoef = 0.04666666666 # (14.0 / 50.0) * (10.0 / 60.0) mk4i reduction
inverted = true

[swerve.steer_fr]
id = 8
[swerve.steer_fl]
id = 6
[swerve.steer_br]
id = 2
[swerve.steer_bl]
id = 4

#Drive
[swerve.drive_fr]
id = 7
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
inverted = false

[swerve.drive_fl]
id = 5
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
inverted = true

[swerve.drive_br]
id = 1
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
inverted = false

[swerve.drive_bl]
id = 3
rotationToMeterCoef = 0.31519599093 # diameter of mk4i L2s * pi
inverted = false


[swerve.abs_fr]
analogChannel = 3
offset = 0.262

[swerve.abs_fl]
analogChannel = 2
offset = 0.709

[swerve.abs_br]
analogChannel = 0
offset = 0.323

[swerve.abs_bl]
analogChannel = 1
offset = 0.011#0.0352701817
