[swerve.steer_pid_common]
p = 30
[swerve.steer_common]
inverted = false
[swerve.drive_fl] #idk
inverted = false
[swerve.drive_fr]
inverted = false
[swerve.drive_bl]
inverted = false
[swerve.drive_br]
inverted = false

